### ISSUE TITLE
Google Images potential issue

### ISSUE THREAD

**Issue by cavejohnsonlemons** [caveljan/holocene-timestamp#1]
I noticed on Chrome that I was having issues with google images loading, and on occasion on google results itself. I tested my extensions and found it was the Holocene extension. My guess is that somehow the substitution is messing with the display? Also, a blacklist of some sort could help to alleviate this problem; for now I'll set the extension to only wikipedia, but I'd like to be able to use it on other sites. Great extension, I love the holocene calendar and thank you for taking the time to read this.

**Comment by ly3xqhl8g9** [comment]
Thank you for the message, and I am happy that you are finding the extension useful.

I also noticed a few days after I ”launched” it that it interferes with Google, it's a tricky bug (the cause is the regular expression for thousands), but since no one seemed interested into using the extension I didn't dedicate time further to debug it. I will have a look as soon as possible to try to fix it.

**Comment by ly3xqhl8g9** [comment]
I updated the extension with a fix: blocking it to run on Google.

I think the reason for the bug is two-fold: Google doesn't like it when you mess with it's search results (sees it as a sort of tampering), the extension makes too much computation to find the year strings. For the first part I can't do anything, but for the second one, I hope I will be able to write an extension that will use natural language processing to find the years in one single parsing of the text.
