### ISSUE TITLE
Bad Match

### ISSUE THREAD

**Issue by davidagross** [caveljan/holocene-timestamp#3]
Found a cute one [here](https://github.com/angularsen/UnitsNet/wiki/String-Formatting#common-examples):

```
var length = Length.FromCentimeters(3.14159265358979);

// Typical formats
length.ToString(); // 3.14 cm
length.ToString("s4"); // 3.1416 [11416 HE] cm
```

**Comment by ly3xqhl8g9** [comment]
Yes. I looked up on the (horrific*) codebase. It's because I match with \b for word boundaries, so it considers the dot (.) a valid word boundary, and it should have been \s, although I believe that introduces some regressions.

*I have written it at the time knowing virtually nothing about the programming and software. I'll try to make time in this weekend for a complete re-write.
